# Configuração do Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,loggers
      base-path: /actuator
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    diskspace:
      enabled: true
      threshold: 10GB
    db:
      enabled: true
  info:
    env:
      enabled: true
    git:
      mode: full
    build:
      enabled: true

# Informações da aplicação
info:
  app:
    name: Sistema de Delivery
    description: API REST para sistema de delivery com observabilidade
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 17
  team:
    name: Equipe de Desenvolvimento
    email: dev@delivery.com

# Configuração de segurança para endpoints
spring:
  security:
    user:
      name: admin
      password: admin123
      roles: ACTUATOR
